language: java
sudo: true

cache:
  directories:
  - $HOME/.m2
  
jdk:
  - oraclejdk8
 
before_install:
 - chmod +x mvnw
 - sudo pip install codecov

script: mvn install

after_success:
  - mvn package jacoco:report coveralls:report

notifications:
email: false
